marks = [90, 87, 67, 76, 66, 55]

print(type(marks))
print(marks)
print(marks[2])
print(marks[0])
print(marks[1:3])
print(marks[:3])
print(marks[3:])
print(marks[-1])
print(marks[::-1])
print(marks[::-2])
print(marks[::2])
marks[5]= 76 #list is mutable
print(marks)int(marks
print(marks.count(90))
print(marks.pop())
print(marks)
print(marks.pop(1))
print(marks)
print(marks.append(89))
print(marks)
print(marks.remove(66))
print(marks)
print(marks.index(67))
print(marks+marks)
pr*3)